version: '3'
services:

  angular-app:
    image: angular-fe-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "61000:80"
    restart: unless-stopped

    flask:
      build: ./flask_conn_db_api
      ports:
        - "5000:5000"
      restart: unless-stopped
